all:
  children:
    rpi5:
      hosts:
        mesoscope:
          # Use IP address if mDNS (mesoscope.local) does not resolve.
          # Requires avahi-daemon running on both client and target.
          ansible_host: 192.168.0.177
          ansible_user: lab
          ansible_ssh_private_key_file: ~/.ssh/prototype
      vars:
        ansible_python_interpreter: /usr/bin/python3
